version: "3.9"

services:
  backend:
    build: ./backend
    container_name: my-story-backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - GOOGLE_CLIENT_ID=110058684309-8a4flsr03gj5da1kssqna09fro1ghrs2.apps.googleusercontent.com
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: my-story-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - EXPO_PUBLIC_API_URL=http://127.0.0.1:8080
      - EXPO_PUBLIC_GOOGLE_CLIENT_ID=110058684309-8a4flsr03gj5da1kssqna09fro1ghrs2.apps.googleusercontent.com
    restart: unless-stopped
